---
abstract: 'serve OpenSearch results'
author:
  - 'Peter Karman, C<< <karman at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: http://dev.perl.org/licenses/
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Search-OpenSearch-Server
no_index:
  directory:
    - inc
    - t
recommends:
  Catalyst::Action::RenderView: 0
  Catalyst::Runtime: 0
requires:
  JSON: 0
  Moose: 0
  Plack: 0
  Search::OpenSearch: '0.400'
  Test::More: 0
  Try::Tiny: 0
  Type::Tiny: 0
  perl: 5.8.3
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Search-OpenSearch-Server
  homepage: https://github.com/karpet/search-opensearch-server
  license: http://opensource.org/licenses/gpl-license.php
  repository: http://github.com/karpet/search-opensearch-server
version: '0.300'
