---
abstract: 'serve OpenSearch results'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Search-OpenSearch-Server
no_index:
  directory:
    - t
    - inc
requires:
  JSON::XS: 0
  Plack: 0
  Search::OpenSearch: 0.15
  Test::More: 0
  perl: 5.008003
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Search-OpenSearch-Server
  homepage: http://perl.peknet.com/
  license: http://dev.perl.org/licenses/
  repository: http://svn.peknet.com/perl/Search-OpenSearch-Server/
version: 0.10
