--- #YAML:1.0
name:               Search-OpenSearch-Server
version:            0.07
abstract:           serve OpenSearch results
author:
    - Peter Karman <karman@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON::XS:            0
    perl:                5.008003
    Plack:               0
    Search::OpenSearch:  0.11
    Test::More:          0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Search-OpenSearch-Server
    homepage:    http://perl.peknet.com/
    license:     http://dev.perl.org/licenses/
    repository:  http://svn.peknet.com/perl/Search-OpenSearch-Server/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
